[package]
name = "solana-loader-v2-interface"
description = "Solana non-upgradable BPF loader v2 instructions."
documentation = "https://docs.rs/solana-loader-v2-interface"
version = "3.0.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:solana-instruction", "serde", "solana-instruction/bincode"]
serde = ["dep:serde", "dep:serde_bytes", "dep:serde_derive"]
stable-abi = [
    "dep:solana-frozen-abi",
    "dep:solana-frozen-abi-macro",
    "serde",
    "solana-frozen-abi-macro/stable-abi",
    "solana-frozen-abi/stable-abi",
]
wincode = [
    "dep:solana-instruction",
    "dep:wincode",
    "solana-instruction/wincode",
    "wincode/alloc",
]

[dependencies]
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-instruction = { workspace = true, features = ["std"], optional = true }
solana-pubkey = { workspace = true }
solana-sdk-ids = { workspace = true }
wincode = { workspace = true, optional = true }

[dev-dependencies]
bincode = { workspace = true }
solana-loader-v2-interface = { path = ".", features = ["bincode", "wincode"] }
solana-pubkey = { workspace = true, features = ["dev-context-only-utils"] }

[lints]
workspace = true
