[package]
name = "solana-account"
description = "Solana Account type"
documentation = "https://docs.rs/solana-account"
version = "5.1.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
bincode = ["dep:bincode", "dep:solana-sysvar", "serde"]
wincode = ["dep:wincode", "solana-pubkey/wincode"]
dev-context-only-utils = ["bincode", "wincode", "dep:qualifier_attr"]
frozen-abi = [
    "solana-frozen-abi-macro/frozen-abi",
    "solana-frozen-abi/frozen-abi",
    "solana-pubkey/frozen-abi",
    "stable-abi",
]
stable-abi = [
    "solana-frozen-abi-macro/stable-abi",
    "solana-frozen-abi/stable-abi",
    "solana-pubkey/stable-abi",
]
serde = ["dep:serde", "dep:serde_bytes", "dep:serde_derive", "solana-pubkey/serde"]

[dependencies]
bincode = { workspace = true, optional = true }
qualifier_attr = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-account-info = { workspace = true }
solana-clock = { workspace = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
solana-instruction-error = { workspace = true }
solana-pubkey = { workspace = true }
solana-sysvar = { workspace = true, optional = true }
wincode = { workspace = true, features = ["alloc"], optional = true }

[dev-dependencies]
solana-account = { path = ".", features = ["dev-context-only-utils"] }
solana-pubkey = { workspace = true, features = ["std"] }
solana-system-interface = { workspace = true }

[lints]
workspace = true
