[package]
name = "solana-inflation"
description = "Configuration for Solana network inflation"
documentation = "https://docs.rs/solana-inflation"
version = "3.3.0"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
all-features = true
rustdoc-args = ["--cfg=docsrs"]

[features]
frozen-abi = ["solana-frozen-abi-macro/frozen-abi", "solana-frozen-abi/frozen-abi", "stable-abi"]
stable-abi = ["solana-frozen-abi-macro/stable-abi", "solana-frozen-abi/stable-abi"]
serde = ["dep:serde", "dep:serde_derive"]
wincode = ["dep:wincode"]

[dependencies]
serde = { workspace = true, optional = true }
serde_derive = { workspace = true, optional = true }
solana-frozen-abi = { workspace = true, optional = true }
solana-frozen-abi-macro = { workspace = true, optional = true }
wincode = { workspace = true, optional = true }

[lints]
workspace = true
